### ISSUE TITLE
enhancement: randomly choose mirrors

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/fetchcommandwrapper#3]
I have an idea: instead of passing the full mirrors list to `aria2c`, why not pass it `n` randomly chosen (`http` or `ftp`) mirrors?
Should dramatically increase the speed when the files are not present in any mirror.

For example if `aria2c` download from 5 mirrors simultaneously, `n` can be 6

**Comment by hartwork** [comment]
Hey!

>  Should dramatically increase the speed when the files are not present in any mirror.

Since we have `--max-file-not-found=2` in by now: is it still slow, for real?

> I have an idea: instead of passing the full mirrors list to aria2c, why not pass it n randomly chosen (http or ftp) mirrors?
> [..]
>
> For example if aria2c download from 5 mirrors simultaneously, n can be 6

There is [use of randomization](https://github.com/gentoo/fetchcommandwrapper/blob/master/modules/fetchcommandwrapper/main.py#L135). We could make [current `MAX_STREAMS = 5`](https://github.com/gentoo/fetchcommandwrapper/blob/master/modules/fetchcommandwrapper/main.py#L8) (which is your `n`) configurable, but I don't see a strong reason to bother, yet.

**Comment by Alessandro-Barbieri** [comment]
Ok, for now behaves  well (after the upgrade)
